name: API Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Install Playwright browsers
        run: uv run playwright install

      - name: Run tests
        run: uv run pytest --alluredir=allure-results

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results